name: schedule

on:
  # schedule:
  #   - cron:  '*/15 * * * *' #永遠に実行され続けるのでコメントアウト

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo This workflow is scheduled
