name: Unit test

on:
  push:
    branches: [ master ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: after checkout
        run: ls

      - name: npm install
        run: npm install

      - name: npm test
        run: npm test
